project_id = "gdddahqvwbgqkikzcvoh"

[functions.admin-manage-user]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.check-user-exists]
verify_jwt = false

[functions.refresh-spark-token]
verify_jwt = false
